//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballSchedulerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int Id { get; set; }
        public int LeagueId { get; set; }
        public System.DateTime TimeOfPlay { get; set; }
        public int HomeTeamId { get; set; }
        public int AwayTeamId { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> AwayScore { get; set; }
    
        public virtual Leagues Leagues { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Teams Teams1 { get; set; }
    }
}
