//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballSchedulerWPF.Windows
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class C__RefactorLog
    {
        public System.Guid OperationKey { get; set; }
    }
}
